src/BIWBACK/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using BIWBACK.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace BIWBACK.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        private IHostingEnvironment _hostingEnvironment;

        public EmployeeController(IHostingEnvironment environment)
        {
            _hostingEnvironment = environment;
        }
        [HttpPost]
        public async Task<IActionResult>  insert_emp(IList<IFormFile> selectFile, string emp_code, string emp_prefix, string emp_name, string emp_lastname, string emp_position, string emp_address, string emp_road, string emp_province, string emp_amphur, string emp_district, string emp_postcode, string emp_tel, string emp_fax, string emp_email, string emp_national_id, string emp_tax, string emp_gender, string emp_birth, string emp_start, string emp_end)
        {
            employeeModel emp = new employeeModel();

            var uploads = Path.Combine(_hostingEnvironment.WebRootPath, "images");
            int num = selectFile.Count();
            if (num != 0)
            {
                foreach (var file in selectFile)
                {
                    if (file.Length > 0)
                    {

                        var filePath = Path.Combine(uploads, file.FileName);
                        emp.emp_img = file.FileName;

                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await file.CopyToAsync(fileStream);

                        }

                    }
                    else
                    {

                        emp.emp_img = "nopicture.jpg";

                    }
                }
            }
            else {

                emp.emp_img = "nopicture.jpg";
            }


            emp.emp_code = emp_code;
            emp.emp_prefix = emp_prefix;
            emp.emp_name = emp_name;
            emp.emp_lastname = emp_lastname;
            emp.emp_position = emp_position;
            emp.emp_address = emp_address;
            emp.emp_road = emp_road;
            emp.emp_district = emp_district;
            emp.emp_amphur = emp_amphur;
            emp.emp_province = emp_province;
            emp.emp_postcode = emp_postcode;
            emp.emp_tel = emp_tel;
            emp.emp_fax = emp_fax;
            emp.emp_email = emp_email;
            emp.emp_national_id = emp_national_id;
            emp.emp_tax = emp_tax;
            emp.emp_gender = emp_gender;
            emp.emp_birthday = emp_birth;
            emp.emp_start_date = emp_start;
            emp.emp_end_date = emp_end;

            emp.insert_emp();


            return RedirectToAction("employee", "Information");
        }
        [HttpPost]
        public async Task<IActionResult> update_emp(IList<IFormFile> selectFile, string emp_img, string emp_code, string emp_prefix, string emp_name, string emp_lastname, string emp_position, string emp_address, string emp_road, string emp_province, string emp_amphur, string emp_district, string emp_postcode, string emp_tel, string emp_fax, string emp_email, string emp_national_id, string emp_tax, string emp_gender, string emp_birth, string emp_start, string emp_end, string emp_id) {

            employeeModel emp = new employeeModel();

            var uploads = Path.Combine(_hostingEnvironment.WebRootPath, "images");

            int num = selectFile.Count();

            if (num != 0)
            {

                foreach (var file in selectFile)
                {
                    if (file.Length > 0)
                    {

                        var filePath = Path.Combine(uploads, file.FileName);
                        emp.emp_img = file.FileName;

                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await file.CopyToAsync(fileStream);

                        }

                    }
                }
            }
            else {

                emp.emp_img = emp_img;

            }
            
            emp.emp_id = emp_id;
            emp.emp_code = emp_code;
            emp.emp_prefix = emp_prefix;
            emp.emp_name = emp_name;
            emp.emp_lastname = emp_lastname;
            emp.emp_position = emp_position;
            emp.emp_address = emp_address;
            emp.emp_road = emp_road;
            emp.emp_district = emp_district;
            emp.emp_amphur = emp_amphur;
            emp.emp_province = emp_province;
            emp.emp_postcode = emp_postcode;
            emp.emp_tel = emp_tel;
            emp.emp_fax = emp_fax;
            emp.emp_email = emp_email;
            emp.emp_national_id = emp_national_id;
            emp.emp_tax = emp_tax;
            emp.emp_gender = emp_gender;
            emp.emp_birthday = emp_birth;
            emp.emp_start_date = emp_start;
            emp.emp_end_date = emp_end;

            emp.update_emp();

            return RedirectToAction("employee","Information");
        }
        public IActionResult editEmployee(string id) {

            employeeModel emp = new employeeModel();
            prefixModel px = new prefixModel();
            provinceModel pv = new provinceModel();
            ampuresModel am = new ampuresModel();
            districts dt = new districts();
            positionModel ps = new positionModel();
            emp.select_emp("emp_id = '"+id+"'");

            ViewData["emp_code"] = emp.emp_code;
            ViewData["emp_prefix"] = px.drop_prefix(emp.emp_prefix);
            ViewData["emp_name"] = emp.emp_name;
            ViewData["emp_lastname"] = emp.emp_lastname;
            ViewData["emp_position"] = ps.drop_position(emp.emp_position);
            ViewData["emp_address"] = emp.emp_address;
            ViewData["emp_road"] = emp.emp_road;
            ViewData["emp_province"] = pv.drop_province(emp.emp_province);
            ViewData["emp_amphur"] = am.dorp_amphur(emp.emp_amphur);
            ViewData["emp_district"] = dt.drop_district(emp.emp_district);
            ViewData["emp_postcode"] = emp.emp_postcode;
            ViewData["emp_tel"] = emp.emp_tel;
            ViewData["emp_fax"] = emp.emp_fax;
            ViewData["emp_email"] = emp.emp_email;
            ViewData["emp_national_id"] = emp.emp_national_id;
            ViewData["emp_gender"] = emp.emp_gender;
            ViewData["emp_tax"] = emp.emp_tax;
            ViewData["emp_birth"] = emp.emp_birthday;
            ViewData["emp_start"] = emp.emp_start_date;
            ViewData["emp_end"] = emp.emp_end_date;
            ViewData["emp_id"] = id;
            if (string.IsNullOrEmpty(emp.emp_img) == true)
            {

                ViewData["emp_img"] = "nopicture.jpg";
            }
            else
            {

                ViewData["emp_img"] = emp.emp_img;
            }

            return View();
        }
        public IActionResult viewEmployee(string id)
        {

            employeeModel emp = new employeeModel();
            prefixModel px = new prefixModel();
            provinceModel pv = new provinceModel();
            ampuresModel am = new ampuresModel();
            districts dt = new districts();
            positionModel ps = new positionModel();
            emp.select_emp("emp_id = '" + id + "'");


            ViewData["emp_code"] = emp.emp_code;
            ViewData["emp_prefix"] = px.drop_prefix(emp.emp_prefix);
            ViewData["emp_name"] = emp.emp_name;
            ViewData["emp_lastname"] = emp.emp_lastname;
            ViewData["emp_position"] = ps.drop_position(emp.emp_position);
            ViewData["emp_address"] = emp.emp_address;
            ViewData["emp_road"] = emp.emp_road;
            ViewData["emp_province"] = pv.drop_province(emp.emp_province);
            ViewData["emp_amphur"] = am.dorp_amphur(emp.emp_amphur);
            ViewData["emp_district"] = dt.drop_district(emp.emp_district);
            ViewData["emp_postcode"] = emp.emp_postcode;
            ViewData["emp_tel"] = emp.emp_tel;
            ViewData["emp_fax"] = emp.emp_fax;
            ViewData["emp_email"] = emp.emp_email;
            ViewData["emp_national_id"] = emp.emp_national_id;
            ViewData["emp_gender"] = emp.emp_gender;
            ViewData["emp_tax"] = emp.emp_tax;
            ViewData["emp_birth"] = emp.emp_birthday;
            ViewData["emp_start"] = emp.emp_start_date;
            ViewData["emp_end"] = emp.emp_end_date;
            ViewData["emp_id"] = id;
            if (string.IsNullOrEmpty(emp.emp_img) == true)
            {

                ViewData["emp_img"] = "nopicture.jpg";
            }
            else
            {

                ViewData["emp_img"] = emp.emp_img;
            }

            return View();
        }
        public void del_emp(string id) {

            employeeModel emp = new employeeModel();
            emp.emp_id = id;
            emp.del_emp();
        }
    }
}

src/BIWBACK/Controllers/LineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BIWBACK.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace BIWBACK.Controllers
{
    public class LineController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public string select_line(string id) {

            lineModel ln = new lineModel();
            ln.select_line("line_id = '"+id+"'");

            return ln.line_code + "^" + ln.line_name;
        }
        public void del_line(string id) {

            lineModel ln = new lineModel();
            ln.line_id = id;
            ln.del_line();
        }
    }
}

src/BIWBACK/Controllers/MashController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BIWBACK.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace BIWBACK.Controllers
{
    public class MashController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult mash()
        {
            MashModel ms = new MashModel();
            ViewData["mash"] = ms.list_mash();

            productModel pd = new productModel();
            ViewData["product"] = pd.drop_product("");

            MaterialModel mt = new MaterialModel();
            ViewData["material"] = mt.drop_mtr("");


            return View();
        }
        
        public IActionResult addMash()
        {
            productModel pd = new productModel();
            ViewData["product"] = pd.drop_product("");
            ViewData["product_list"] = pd.list_product();

            MaterialModel mt = new MaterialModel();
            ViewData["material"] = mt.drop_mtr("");
            
            return View();
        }
        public IActionResult modelMash()
        {
            MashModelProductModel mmp = new MashModelProductModel();
            ViewData["mmp"] = mmp.list_mmp();

            MaterialModel mt = new MaterialModel();
            ViewData["material"] = mt.drop_mtr("");

            modelProductModel mpd = new modelProductModel();
            ViewData["modelProduct"] = mpd.drop_mp("");

            return View();
        }
        public IActionResult addModelMash()
        {

            MaterialModel mt = new MaterialModel();
            ViewData["material"] = mt.drop_mtr("");

            modelProductModel mpd = new modelProductModel();
            ViewData["modelProduct"] = mpd.drop_mp("");
            ViewData["modelProduct_list"] = mpd.list_mp();
            

            return View();
        }
        [HttpPost]
        public IActionResult insertMash(IEnumerable<string> material_id, IEnumerable<string> product_id) {

            int length = material_id.Count();

            List<string> product = new List<string>();
            List<string> material = new List<string>();

            foreach (string p in product_id) {

                product.Add(p);

            }
            foreach (string m in material_id)
            {

                material.Add(m);

            }

            int i = 0;
            for (i = 0; i < length; i++) {

                MashModel ms = new MashModel();
                ms.mash_ref_product_id = product[i];
                ms.mash_ref_material_id = material[i];
                ms.insert_mash();
            }
            


            return RedirectToAction("mash","Mash");
        }
        public string select_mash(string id) {

            MashModel ms = new MashModel();
            ms.select_mash("mash_id = '"+id+"'");

            return ms.mash_ref_product_id + "^" + ms.mash_ref_material_id;
        }
        public void del_mash(string id) {


            MashModel ms = new MashModel();
            ms.mash_id = id;
            ms.del_mash();
        }
        [HttpPost]
        public IActionResult update_mash(string product, string material, string mash_id) {

            MashModel ms = new MashModel();
            ms.mash_id = mash_id;
            ms.mash_ref_product_id = product;
            ms.mash_ref_material_id = material;
            ms.update_mash();
            
            return RedirectToAction("mash","Mash");
        }
        ///mash model product
        ///
        [HttpPost]
        public IActionResult insertModelMash(IEnumerable<string> material_id, IEnumerable<string> modelproduct_id)
        {
         
            int length = material_id.Count();

            List<string> modelProduct = new List<string>();
            List<string> material = new List<string>();

            foreach (string mp in modelproduct_id)
            {

                modelProduct.Add(mp);

            }
            foreach (string m in material_id)
            {

                material.Add(m);

            }

            int i = 0;
            for (i = 0; i < length; i++)
            {
                MashModelProductModel mmp = new MashModelProductModel();

                mmp.mmp_ref_material_id = material[i];
                mmp.mmp_ref_model_product_id = modelProduct[i];

                mmp.insert_mmp();
            }



            return RedirectToAction("modelMash", "Mash");
        }
        [HttpPost]
        public IActionResult update_mmp(string material, string modelProduct, string mmp_id) {


            MashModelProductModel mmp = new MashModelProductModel();
            mmp.mmp_id = mmp_id;
            mmp.mmp_ref_model_product_id = modelProduct;
            mmp.mmp_ref_material_id = material;
            mmp.update_mmp();


            return RedirectToAction("modelMash","Mash");
        }
        public string select_mmp(string id) {

            MashModelProductModel mmp = new MashModelProductModel();
            mmp.select_mmp("mmp_id = '"+id+"'");


            return mmp.mmp_ref_material_id + "^" + mmp.mmp_ref_model_product_id;
        }
        public void del_mmp(string id) {

            MashModelProductModel mmp = new MashModelProductModel();
            mmp.mmp_id = id;
            mmp.del_mmp();

        }
    }
}

src/BIWBACK/Controllers/ProvinceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace BIWBACK.Controllers
{
    public class ProvinceController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/BIWBACK/Controllers/TypePaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BIWBACK.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace BIWBACK.Controllers
{
    public class TypePaymentController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult insert_type_payment(string type_pay) {

            typePaymentModel tp = new typePaymentModel();
            tp.tp_name = type_pay;
            tp.insert_type_payment();

            return RedirectToAction("typePayment","Information");
        }
        [HttpPost]
        public IActionResult update_type_payment(string type_pay_edit, string type_pay_id)
        {

            typePaymentModel tp = new typePaymentModel();
            tp.tp_name = type_pay_edit;
            tp.tp_id = type_pay_id;
            tp.update_type_payment();

            return RedirectToAction("typePayment", "Information");
        }
        public string select_type_payment(string id) {

            typePaymentModel tp = new typePaymentModel();
            tp.select_type_payment("tp_id = '"+id+"'");

            return tp.tp_name;
        }
        public void del_type_payment(string id) {

            typePaymentModel tp = new typePaymentModel();
            tp.tp_id = id;
            tp.del_type_payment();
        }
    }
}

src/BIWBACK/Views/Information/employee.cshtml
@{
    Layout = "_Layout";
}
<!-- Content Header (Page header) -->
@using BIWBACK.Models

<section class="content-header">
    <h1>
        พนักงาน
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> ข้อมูลหลัก</a></li>
        <li class="active">  พนักงาน</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">   พนักงาน</h3>
                </div>
                <!-- /.box-header -->
                <div class="text-right">
                    <a href="@Url.Action("addEmployee", "Information")" class="btn btn-primary"><i class="fa fa-plus-square-o"></i> เพิ่ม  พนักงาน</a>
                    <br /><br />
                </div>
                <div class="box-body">

                    <table id="example2" class="table table-bordered data_table">
                        <thead>
                            <tr>
                                <th>ลำดับ</th>
                                <th>รูปประจำตัว</th>
                                <th>รหัส</th>
                                <th>ชื่อ-สกุล</th>
                                <th>ตำแหน่ง</th>
                                <th>จังหวัด</th>
                                <th>วันเข้างาน</th>
                                <th>วันลาออก</th>
                                <th>สถานะ</th>
                                <th>จัดการ</th>


                            </tr>
                        </thead>
                        <tbody>
                            @{ int i = 1;}
                            @foreach (var item in ViewData["employee"] as List<employeeModel>)
                            {
                            <tr>
                                
                                <td>@i</td>
                                <td>
                                    @if (string.IsNullOrEmpty(item.emp_img) == true)
                                    {

                                        <img src="~/images/nopicture.jpg" height="90px" width="90px"/>
                                    }
                                    else
                                    {
                                        <img src="~/images/@item.emp_img" height="90px" width="90px"/>

                                    }
                                    
                                </td>
                                <td>@item.emp_code</td>
                                <td>@item.emp_name @item.emp_lastname</td>
                                <td>@item.emp_position</td>
                                <td>@item.emp_province</td>
                                <td>@Convert.ToDateTime(item.emp_start_date).ToString("dd/MM/yyyy")</td>
                                <td>@item.emp_end_date</td>

                                @if (item.emp_status == "ดำเนินการ")
                                {

                                    <td><button class="btn btn-info"><span class="text-green"><i class="fa fa-fw fa-circle"></i></span> @item.emp_status </button></td>

                                }
                                else
                                {
                                    <td><button class="btn btn-warning"><span class="text-red"><i class="fa fa-fw fa-circle"></i></span> @item.emp_status </button></td>


                                }


                                
                                <td>
                                    <a href="@Url.Action("viewEmployee", "Employee", new { id = item.emp_id})" class="btn btn-primary view_emp" ref="@item.emp_id"><i class="fa fa-file"></i> รายละเอียด</a>
                                    <a href="@Url.Action("editEmployee", "Employee", new { id = item.emp_id})" class="btn btn-warning edit_emp" ref="@item.emp_id"><i class="fa fa-edit"></i> แก้ไข</a>
                                    <a class="btn btn-danger del_emp" ref="@item.emp_id"><i class="fa fa-trash"></i> ลบ</a>
                                </td>
                            </tr>
                                i++;
                            }
                           </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </div>
        <!-- /.col -->
    </div>
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
<script src="~/lib/jquery/dist/jquery-3.2.1.min.js"></script>
<script>
    $(document).on('click', '.del_emp', function () {

        var x = $(this).attr('ref');

        swal({
            title: "คุณต้องการลบข้อมูลนี้ใช่หรือไม่?",
           // text: "คุณจะไม่่สามารถ",
            type: "warning",
            showCancelButton: true,
            confirmButtonClass: "btn-danger",
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel plx!",
            closeOnConfirm: false,
            closeOnCancel: false
        },
function (isConfirm) {
    if (isConfirm) {

        $.get('../../Employee/del_emp?id=' + x, function () {

            swal("ลบข้อมูลเรียบร้อย!", "", "success");
            location.reload();
        })

    } else {
        swal("ยกเลิก", "", "error");
    }
});


    })
</script>

src/BIWBACK/Views/Information/typePayment.cshtml
@{
    Layout = "_Layout";
}
<!-- Content Header (Page header) -->
@using BIWBACK.Models
<section class="content-header">
    <h1>
        ประเภทการชำระเงิน
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> ข้อมูลหลัก</a></li>
        <li class="active">  ประเภทการชำระเงิน</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">   ประเภทการชำระเงิน</h3>
                </div>
                <!-- /.box-header -->
                <div class="text-right">
                    <a class="btn btn-primary" data-toggle="modal" data-target="#Mymodal"><i class="fa fa-plus-square-o"></i> เพิ่ม  ประเภทการชำระเงิน</a>
                    <br /><br />
                </div>
                <div class="box-body">

                    <!--Modal-->
                    <div class="modal fade" id="Mymodal">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    <h4 class="modal-title">เพิ่ม  ประเภทการชำระเงิน</h4>
                                </div>
                                <div class="modal-body">
                                    @{ Html.BeginForm("insert_type_payment", "TypePayment", FormMethod.Post);}
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-sm-2">
                                                ชำระโดย
                                            </div>
                                            <div class="col-sm-10">
                                              @Html.TextBox("type_pay", "", new { @class = "form-control" })
                                            </div>
                                           
                                        </div>
                                    </div>

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">ยกเลิก</button>
                                      <button type="submit" class="btn btn-primary"><span><i class="fa fa-save"></i> บันทึก</span></button>
                                    </div>
                                    @{ Html.EndForm();}
                                </div>

                                <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                        </div>
                    </div>
                    <!-- /.modal -->


                    <table  class="table table-bordered data_table">
                        <thead>
                            <tr>
                                <th>ลำดับ</th>
                                <th>ประเภทการชำระเงิน</th>
                                <th>จัดการ</th>

                            </tr>
                        </thead>
                        <tbody>
                            @{ int i = 1;}
                            @foreach (var item in ViewData["type_payment"] as List<typePaymentModel>)
                            {
                            <tr>

                                <td>@i</td>
                                <td>@item.tp_name</td>
                                <td>
                                    <a class="btn btn-warning edit_tp" ref="@item.tp_id" data-toggle="modal" data-target="#MymodalEditTypePayment"><i class="fa fa-edit"></i> แก้ไข</a>
                                    <a class="btn btn-danger del_tp" ref="@item.tp_id"><i class="fa fa-trash"></i> ลบ</a>
                                </td>

                            </tr>
                                i++;
                            }
                            </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
            <!--Modal edit-->
            <div class="modal fade" id="MymodalEditTypePayment">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title">แก้ไข  ประเภทการชำระเงิน</h4>
                        </div>
                        <div class="modal-body">
                            @{ Html.BeginForm("update_type_payment", "TypePayment", FormMethod.Post);}
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-sm-2">
                                        ชำระโดย
                                    </div>
                                    <div class="col-sm-10">
                                        @Html.TextBox("type_pay_edit", "", new { @class = "form-control" })
                                        @Html.TextBox("type_pay_id", "", new { @class = "form-control",@type="hidden" })
                                    </div>

                                </div>
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">ยกเลิก</button>
                                <button type="submit" class="btn btn-primary"><span><i class="fa fa-save"></i> บันทึก</span></button>
                            </div>
                            @{ Html.EndForm();}
                        </div>

                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
            </div>
            <!-- /.modal -->
        </div>
        <!-- /.col -->
    </div>
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
<script src="~/lib/jquery/dist/jquery-3.2.1.min.js"></script>
<script>
    $(document).on('click', '.edit_tp', function () {

        var x = $(this).attr('ref');

        $('#type_pay_id').val(x);

        $.get('../../TypePayment/select_type_payment?id=' + x, function (data) {


            $('#type_pay_edit').val(data);

        })


    })
</script>
<script>
    $(document).on('click', '.del_tp', function () {

        var x = $(this).attr('ref');

        swal({
            title: "คุณต้องการลบข้อมูลนี้ใช่หรือไม่?",
            // text: "คุณจะไม่่สามารถ",
            type: "warning",
            showCancelButton: true,
            confirmButtonClass: "btn-danger",
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel plx!",
            closeOnConfirm: false,
            closeOnCancel: false
        },
        function (isConfirm) {
            if (isConfirm) {

                $.get('../../TypePayment/del_type_payment?id=' + x, function () {

                    swal("ลบข้อมูลเรียบร้อย!", "", "success");
                    location.reload();
                })

            } else {
                swal("ยกเลิก", "", "error");
            }
        });

    });
</script> 